# Generated by Django 4.0.4 on 2022-05-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceOfRegistrationForDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=110, verbose_name='Регион проживания')),
                ('idRegion', models.CharField(max_length=110, verbose_name='ID региона')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceOfRegistrationForLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=110, verbose_name='Регион проживания')),
                ('idRegion', models.CharField(max_length=110, verbose_name='ID региона')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceOfResidenceForDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=110, verbose_name='Место жительства')),
                ('idRegion', models.CharField(max_length=110, verbose_name='ID региона')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceOfResidenceForLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=110, verbose_name='Место жительства')),
                ('idRegion', models.CharField(max_length=110, verbose_name='ID региона')),
            ],
        ),
    ]
