# Generated by Django 4.0.4 on 2022-05-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anketaPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeofregistrationfordeal',
            options={'verbose_name_plural': 'СДЕЛКА Регион проживания'},
        ),
        migrations.AlterModelOptions(
            name='placeofregistrationforlead',
            options={'verbose_name_plural': 'ЛИД Регин проживания'},
        ),
        migrations.AlterModelOptions(
            name='placeofresidencefordeal',
            options={'verbose_name_plural': 'СДЕЛКА Место жительства'},
        ),
        migrations.AlterModelOptions(
            name='placeofresidenceforlead',
            options={'verbose_name_plural': 'ЛИД Место жительства'},
        ),
        migrations.AlterField(
            model_name='placeofregistrationfordeal',
            name='idRegion',
            field=models.IntegerField(max_length=7, verbose_name='ID региона'),
        ),
        migrations.AlterField(
            model_name='placeofregistrationfordeal',
            name='region',
            field=models.CharField(max_length=110, verbose_name='Регион проживания Сделка'),
        ),
        migrations.AlterField(
            model_name='placeofregistrationforlead',
            name='idRegion',
            field=models.IntegerField(max_length=7, verbose_name='ID региона'),
        ),
        migrations.AlterField(
            model_name='placeofregistrationforlead',
            name='region',
            field=models.CharField(max_length=110, verbose_name='Регион проживания Лид'),
        ),
        migrations.AlterField(
            model_name='placeofresidencefordeal',
            name='idRegion',
            field=models.IntegerField(max_length=7, verbose_name='ID региона'),
        ),
        migrations.AlterField(
            model_name='placeofresidencefordeal',
            name='region',
            field=models.CharField(max_length=110, verbose_name='Место жительства Сделка'),
        ),
        migrations.AlterField(
            model_name='placeofresidenceforlead',
            name='idRegion',
            field=models.IntegerField(max_length=7, verbose_name='ID региона'),
        ),
        migrations.AlterField(
            model_name='placeofresidenceforlead',
            name='region',
            field=models.CharField(max_length=110, verbose_name='Место жительства Лид'),
        ),
    ]
